version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 568658500942.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=568658500942.dkr.ecr.us-east-1.amazonaws.com/bia
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - |
        echo "{
          \"AWSEBDockerrunVersion\": 1,
          \"Image\": {
            \"Name\": \"$REPOSITORY_URI:$IMAGE_TAG\",
            \"Update\": true
          },
          \"Ports\": [
            {
              \"ContainerPort\": 3000
            }
          ]
        }" > Dockerrun.aws.json
      - zip -r output.zip Dockerrun.aws.json

artifacts:
  files:
    - output.zip
