version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 21 e npm...      
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash -
      - sudo yum install -y nodejs
  build:
    commands:
      - echo Instalando o NPM
      - npm install --loglevel=error
      - REACT_APP_API_URL=http://localhost:3001 SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - Rodando testes unitários
      - npm test