 version: 0.2
 
 phases:
 pre_build:
     commands:
      - echo "Fazendo login no ECR..."      
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 277519277676.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=277519277676.dkr.ecr.us-east-2.amazonaws.com/bia
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
 build:
     commands:
      - echo "Build iniciado em `date`"
      - echo "Gerando imagem da BIA..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
 post_build:
     commands:
       - echo "Build finalizado com sucesso em `date`"
       - echo "Fazendo push da imagem para o ECR..."
       - docker push $REPOSITORY_URI:latest
       - docker push $REPOSITORY_URI:$IMAGE_TAG
       - echo "Gerando imagedefinitions.json para Elastic Beanstalk..."
       - printf '[{"name":"bia","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
       - cat imagedefinitions.json
 
 artifacts:
   files:
      - imagedefinitions.json
