services:
  server:
    build: .
    container_name: bia
    ports:
      - 3001:8080
    environment:
      DB_USER: postgres
      DB_PWD: Ajkluj65z3s3GLCI5CIY
      DB_HOST: bia.c4zy4cykm0n7.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
     ## NAO PRECISA NO BOOTCAMP DAQUI PRA BAIXO ##
      # DB_SECRET_NAME: 
      # DB_REGION: 
      # AWS_ACCESS_KEY_ID: 
      # AWS_SECRET_ACCESS_KEY:
      # DEBUG_SECRET: 
      # IS_LOCAL: true
