version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
  build:
    commands:
      - npm install --loglevel=error
      - REACT_APP_API_URL=http://localhost:3001 SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - echo Rodando testes unitários
      - npm test