name: Testes Unitários

on:
  pull_request:
    branches:
      - ia-main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes unitários
        run: npm test
